application: plusfeed
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: plusfeed.py

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  
- url: /.+
  script: plusfeed.py